/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dam.Model;
using dam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dam.Test.Model
{
    /// <summary>
    ///  Class for testing BatchUploadAssetsRequestFiles
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchUploadAssetsRequestFilesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchUploadAssetsRequestFiles
        //private BatchUploadAssetsRequestFiles instance;

        public BatchUploadAssetsRequestFilesTests()
        {
            // TODO uncomment below to create an instance of BatchUploadAssetsRequestFiles
            //instance = new BatchUploadAssetsRequestFiles();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchUploadAssetsRequestFiles
        /// </summary>
        [Fact]
        public void BatchUploadAssetsRequestFilesInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchUploadAssetsRequestFiles
            //Assert.IsType<BatchUploadAssetsRequestFiles>(instance);
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Fact]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
    }
}
