/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dam.Model;
using dam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dam.Test.Model
{
    /// <summary>
    ///  Class for testing DamAssetType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DamAssetTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DamAssetType
        //private DamAssetType instance;

        public DamAssetTypeTests()
        {
            // TODO uncomment below to create an instance of DamAssetType
            //instance = new DamAssetType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DamAssetType
        /// </summary>
        [Fact]
        public void DamAssetTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" DamAssetType
            //Assert.IsType<DamAssetType>(instance);
        }
    }
}
