/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dam.Model;
using dam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dam.Test.Model
{
    /// <summary>
    ///  Class for testing DamBatchUploadAssetsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DamBatchUploadAssetsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DamBatchUploadAssetsResponse
        //private DamBatchUploadAssetsResponse instance;

        public DamBatchUploadAssetsResponseTests()
        {
            // TODO uncomment below to create an instance of DamBatchUploadAssetsResponse
            //instance = new DamBatchUploadAssetsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DamBatchUploadAssetsResponse
        /// </summary>
        [Fact]
        public void DamBatchUploadAssetsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DamBatchUploadAssetsResponse
            //Assert.IsType<DamBatchUploadAssetsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PreSignedUrls'
        /// </summary>
        [Fact]
        public void PreSignedUrlsTest()
        {
            // TODO unit test for the property 'PreSignedUrls'
        }
    }
}
