/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dam.Model;
using dam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dam.Test.Model
{
    /// <summary>
    ///  Class for testing DamCreateAssetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DamCreateAssetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DamCreateAssetRequest
        //private DamCreateAssetRequest instance;

        public DamCreateAssetRequestTests()
        {
            // TODO uncomment below to create an instance of DamCreateAssetRequest
            //instance = new DamCreateAssetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DamCreateAssetRequest
        /// </summary>
        [Fact]
        public void DamCreateAssetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DamCreateAssetRequest
            //Assert.IsType<DamCreateAssetRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
    }
}
