/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dam.Model;
using dam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dam.Test.Model
{
    /// <summary>
    ///  Class for testing DamListAssetsByIdsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DamListAssetsByIdsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DamListAssetsByIdsRequest
        //private DamListAssetsByIdsRequest instance;

        public DamListAssetsByIdsRequestTests()
        {
            // TODO uncomment below to create an instance of DamListAssetsByIdsRequest
            //instance = new DamListAssetsByIdsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DamListAssetsByIdsRequest
        /// </summary>
        [Fact]
        public void DamListAssetsByIdsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DamListAssetsByIdsRequest
            //Assert.IsType<DamListAssetsByIdsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Fact]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }
    }
}
