/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dam.Model;
using dam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dam.Test.Model
{
    /// <summary>
    ///  Class for testing DamListAssetsByIdsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DamListAssetsByIdsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DamListAssetsByIdsResponse
        //private DamListAssetsByIdsResponse instance;

        public DamListAssetsByIdsResponseTests()
        {
            // TODO uncomment below to create an instance of DamListAssetsByIdsResponse
            //instance = new DamListAssetsByIdsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DamListAssetsByIdsResponse
        /// </summary>
        [Fact]
        public void DamListAssetsByIdsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DamListAssetsByIdsResponse
            //Assert.IsType<DamListAssetsByIdsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }
    }
}
