/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dam.Model;
using dam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dam.Test.Model
{
    /// <summary>
    ///  Class for testing DamUpdateAssetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DamUpdateAssetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DamUpdateAssetRequest
        //private DamUpdateAssetRequest instance;

        public DamUpdateAssetRequestTests()
        {
            // TODO uncomment below to create an instance of DamUpdateAssetRequest
            //instance = new DamUpdateAssetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DamUpdateAssetRequest
        /// </summary>
        [Fact]
        public void DamUpdateAssetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DamUpdateAssetRequest
            //Assert.IsType<DamUpdateAssetRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'PayloadMask'
        /// </summary>
        [Fact]
        public void PayloadMaskTest()
        {
            // TODO unit test for the property 'PayloadMask'
        }
    }
}
