/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dam.Model;
using dam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dam.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateAssetRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAssetRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateAssetRequestPayload
        //private UpdateAssetRequestPayload instance;

        public UpdateAssetRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of UpdateAssetRequestPayload
            //instance = new UpdateAssetRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateAssetRequestPayload
        /// </summary>
        [Fact]
        public void UpdateAssetRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateAssetRequestPayload
            //Assert.IsType<UpdateAssetRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
