/*
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using dam.Client;
using dam.Api;
// uncomment below to import models
//using dam.Model;

namespace dam.Test.Api
{
    /// <summary>
    ///  Class for testing BasicOperationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BasicOperationsApiTests : IDisposable
    {
        private BasicOperationsApi instance;

        public BasicOperationsApiTests()
        {
            instance = new BasicOperationsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BasicOperationsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BasicOperationsApi
            //Assert.IsType<BasicOperationsApi>(instance);
        }

        /// <summary>
        /// Test BatchUploadAssets
        /// </summary>
        [Fact]
        public void BatchUploadAssetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamBatchUploadAssetsRequest body = null;
            //var response = instance.BatchUploadAssets(body);
            //Assert.IsType<DamBatchUploadAssetsResponse>(response);
        }

        /// <summary>
        /// Test BatchUploadAssets_0
        /// </summary>
        [Fact]
        public void BatchUploadAssets_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamBatchUploadAssetsRequest body = null;
            //var response = instance.BatchUploadAssets_0(body);
            //Assert.IsType<DamBatchUploadAssetsResponse>(response);
        }

        /// <summary>
        /// Test CreateAsset
        /// </summary>
        [Fact]
        public void CreateAssetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamCreateAssetRequest body = null;
            //var response = instance.CreateAsset(body);
            //Assert.IsType<DamAsset>(response);
        }

        /// <summary>
        /// Test CreateAsset_0
        /// </summary>
        [Fact]
        public void CreateAsset_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamCreateAssetRequest body = null;
            //var response = instance.CreateAsset_0(body);
            //Assert.IsType<DamAsset>(response);
        }

        /// <summary>
        /// Test GetAssetByCode
        /// </summary>
        [Fact]
        public void GetAssetByCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamGetAssetByCodeRequest body = null;
            //var response = instance.GetAssetByCode(body);
            //Assert.IsType<DamAsset>(response);
        }

        /// <summary>
        /// Test GetAssetByCode_0
        /// </summary>
        [Fact]
        public void GetAssetByCode_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamGetAssetByCodeRequest body = null;
            //var response = instance.GetAssetByCode_0(body);
            //Assert.IsType<DamAsset>(response);
        }

        /// <summary>
        /// Test ListAssets
        /// </summary>
        [Fact]
        public void ListAssetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamListAssetsRequest body = null;
            //var response = instance.ListAssets(body);
            //Assert.IsType<DamListAssetsResponse>(response);
        }

        /// <summary>
        /// Test ListAssetsByCodes
        /// </summary>
        [Fact]
        public void ListAssetsByCodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamListAssetsByCodesRequest body = null;
            //var response = instance.ListAssetsByCodes(body);
            //Assert.IsType<DamListAssetsByCodesResponse>(response);
        }

        /// <summary>
        /// Test ListAssetsByCodes_0
        /// </summary>
        [Fact]
        public void ListAssetsByCodes_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamListAssetsByCodesRequest body = null;
            //var response = instance.ListAssetsByCodes_0(body);
            //Assert.IsType<DamListAssetsByCodesResponse>(response);
        }

        /// <summary>
        /// Test ListAssetsByIds
        /// </summary>
        [Fact]
        public void ListAssetsByIdsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamListAssetsByIdsRequest body = null;
            //var response = instance.ListAssetsByIds(body);
            //Assert.IsType<DamListAssetsByIdsResponse>(response);
        }

        /// <summary>
        /// Test ListAssetsByIds_0
        /// </summary>
        [Fact]
        public void ListAssetsByIds_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamListAssetsByIdsRequest body = null;
            //var response = instance.ListAssetsByIds_0(body);
            //Assert.IsType<DamListAssetsByIdsResponse>(response);
        }

        /// <summary>
        /// Test ListAssets_0
        /// </summary>
        [Fact]
        public void ListAssets_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamListAssetsRequest body = null;
            //var response = instance.ListAssets_0(body);
            //Assert.IsType<DamListAssetsResponse>(response);
        }

        /// <summary>
        /// Test UpdateAsset
        /// </summary>
        [Fact]
        public void UpdateAssetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamUpdateAssetRequest body = null;
            //var response = instance.UpdateAsset(body);
            //Assert.IsType<DamAsset>(response);
        }

        /// <summary>
        /// Test UpdateAsset_0
        /// </summary>
        [Fact]
        public void UpdateAsset_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DamUpdateAssetRequest body = null;
            //var response = instance.UpdateAsset_0(body);
            //Assert.IsType<DamAsset>(response);
        }
    }
}
